"""first generation

Revision ID: 2664489b2be4
Revises: 
Create Date: 2026-07-14 15:10:28.632789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2664489b2be4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Author_id'), 'Author', ['id'], unique=False)
    op.create_table('Bookstore',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Bookstore_id'), 'Bookstore', ['id'], unique=False)
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Genre_id'), 'Genre', ['id'], unique=False)
    op.create_table('Publisher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Publisher_id'), 'Publisher', ['id'], unique=False)
    op.create_table('Test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('example_field_1', sa.String(), nullable=True),
    sa.Column('example_field_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Test_id'), 'Test', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('Book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre'], ['Genre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Book_id'), 'Book', ['id'], unique=False)
    op.create_table('Edition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('publisher', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('bookstore', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookstore'], ['Bookstore.id'], ),
    sa.ForeignKeyConstraint(['publisher'], ['Publisher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Edition_id'), 'Edition', ['id'], unique=False)
    op.create_table('Order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Order_id'), 'Order', ['id'], unique=False)
    op.create_table('Subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Subscription_id'), 'Subscription', ['id'], unique=False)
    op.create_table('IntellectualProperty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['Author.id'], ),
    sa.ForeignKeyConstraint(['book'], ['Book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IntellectualProperty_id'), 'IntellectualProperty', ['id'], unique=False)
    op.create_table('RentedBook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_rented', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order'], ['Order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RentedBook_id'), 'RentedBook', ['id'], unique=False)
    op.create_table('Penalty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('subscription', sa.Integer(), nullable=True),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['RentedBook.id'], ),
    sa.ForeignKeyConstraint(['subscription'], ['Subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Penalty_id'), 'Penalty', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Penalty_id'), table_name='Penalty')
    op.drop_table('Penalty')
    op.drop_index(op.f('ix_RentedBook_id'), table_name='RentedBook')
    op.drop_table('RentedBook')
    op.drop_index(op.f('ix_IntellectualProperty_id'), table_name='IntellectualProperty')
    op.drop_table('IntellectualProperty')
    op.drop_index(op.f('ix_Subscription_id'), table_name='Subscription')
    op.drop_table('Subscription')
    op.drop_index(op.f('ix_Order_id'), table_name='Order')
    op.drop_table('Order')
    op.drop_index(op.f('ix_Edition_id'), table_name='Edition')
    op.drop_table('Edition')
    op.drop_index(op.f('ix_Book_id'), table_name='Book')
    op.drop_table('Book')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Test_id'), table_name='Test')
    op.drop_table('Test')
    op.drop_index(op.f('ix_Publisher_id'), table_name='Publisher')
    op.drop_table('Publisher')
    op.drop_index(op.f('ix_Genre_id'), table_name='Genre')
    op.drop_table('Genre')
    op.drop_index(op.f('ix_Bookstore_id'), table_name='Bookstore')
    op.drop_table('Bookstore')
    op.drop_index(op.f('ix_Author_id'), table_name='Author')
    op.drop_table('Author')
    # ### end Alembic commands ###
